version: "3"
services:
#    redis:
#      image: redis:alpine
#      container_name: app-redis
#      restart: always

#    mailhog:
#      image: phpdockerio/mailhog:latest
#      container_name: app-mailhog
#      ports:
#        - "8125:8025"

    mariadb:
      image: mariadb:10.1
      container_name: app-mariadb
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - "8306:3306"

    nginx:
      image: nginx:alpine
      container_name: app-nginx
      volumes:
        - ./app:/var/www/app
        - ./logs/nginx:/var/log/nginx
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8080:80"
        - "8443:443"
      links:
        - phpfpm

    phpfpm:
      build:
        context: .
        dockerfile: phpdocker/php-fpm/Dockerfile
      container_name: app-php-fpm
      volumes:
        - ./app:/var/www/app
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      links:
        - mariadb
